spring.datasource.url=jdbc:postgresql://dpg-d6pb9o75r7bs73fdt5r0-a/rh_database_85z6
spring.datasource.username=rh_database_85z6_user
spring.datasource.password=nLRqGcoEW0MrPzQT1LywZILHOxRLqOSR

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
server.port=${PORT:8080}